### ISSUE TITLE
CSS example?

### ISSUE THREAD

**Issue by skaraman** [exsdk/example-apps#6]
Any example that uses css files?

I've tried setting up my own using `style-loader` and `css-loader` but I seem to be running into an issue where I can't insert css into `ui-panel-frame::shadow` because shadow doesn't exist when package is loaded

**Comment by skaraman** [comment]
I worked around this with 

webpack.config.js
```
{
	loader: 'style-loader',
	options: {
		insertInto: '#panel-id',
		transform: './panel/util/transform'
	}
}
```
panel/util/transform.js
```
module.exports = function myTransform(css){
	const trans = css.replace(/\./g,'#panel-id::shadow .')
	return trans;
}
```

**Comment by jwu** [comment]
Hello @skaraman , this project is deprecated. May be you can go to check https://github.com/electron-utils, this is where I start a similar project. And the way I handle css can be found in https://github.com/electron-utils/electron-ui-kit
